from jinja2 import Template
import os
from datetime import datetime

TEMPLATE = """
<!DOCTYPE html>
<html lang="{{ language }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tech & AI Daily Brief</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            background-color: #f4f4f9;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            padding: 40px 0;
        }
        .header h1 {
            margin: 0;
            font-size: 2.5em;
            color: #2c3e50;
        }
        .header p {
            color: #7f8c8d;
        }
        .card {
            background: white;
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 24px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
            transition: transform 0.2s;
        }
        .card:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 12px rgba(0,0,0,0.08);
        }
        .card-title {
            margin-top: 0;
            font-size: 1.4em;
            color: #2980b9;
        }
        .card-title a {
            text-decoration: none;
            color: inherit;
        }
        .card-title a:hover {
            text-decoration: underline;
        }
        .source-tag {
            display: inline-block;
            background: #e8f4f8;
            color: #2980b9;
            padding: 4px 10px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: 600;
            margin-bottom: 15px;
        }
        .summary {
            font-size: 1.05em;
            color: #34495e;
            white-space: pre-wrap;
        }
        .footer {
            text-align: center;
            margin-top: 50px;
            color: #95a5a6;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ title }}</h1>
        <p>{{ date }}</p>
    </div>
    
    <div class="content">
        {% for item in items %}
        <div class="card">
            <div class="source-tag">{{ item.source }}</div>
            <h2 class="card-title"><a href="{{ item.url }}" target="_blank">{{ item.title }}</a></h2>
            <div class="summary">{{ item.summary if item.summary else item.description }}</div>
        </div>
        {% else %}
        <div class="card">
            <p style="text-align: center; color: #7f8c8d;">今天还没有新内容更新哦。Check back tomorrow!</p>
        </div>
        {% endfor %}
    </div>
    
    <div class="footer">
        <p>Generated by AI News Push Service | <a href="feed.xml">RSS Feed</a></p>
    </div>
</body>
</html>
"""

def build_webpage(items, output_file='index.html', language='zh'):
    template = Template(TEMPLATE)
    
    html = template.render(
        language=language,
        title="科技与AI每日速递" if language == 'zh' else "Tech & AI Daily Brief",
        date=datetime.now().strftime('%Y-%m-%d'),
        items=items
    )
    
    os.makedirs(os.path.dirname(output_file) or '.', exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"Generated HTML webpage at {output_file}")
